suppressMessages({
  library(tidyverse)
  library(cli)
  library(sf)
  library(redist)
  library(geomander)
  library(wacolors)
  library(patchwork)
  library(scales)
  library(ggrepel)
  library(censable)
  library(ppmf)
  library(here)
  library(geojsonsf)
  library(fs)
  library(glue)
  library(ggtext)
  library(ggredist)
  library(httr)
  library(jsonlite)
  library(osrm)
  library(assertthat)
  library(tidyr)
  source("R/utils/utils.R")
})

cli_alert_success("Packages loaded and utilities prepared.")